#!/bin/sh

# Get Linux ARCH from Morph architecture

if [ -z "$MORPH_ARCH" ]; then
    echo "Error: MORPH_ARCH is not set" >&2
    exit 1
fi

case "$MORPH_ARCH" in
    armv7b|armv7l|armv7lhf)
        echo arm ;;
    x86_32)
        echo i386 ;;
    x86_64)
        echo x86_64 ;;
    ppc64)
        echo powerpc ;;
    mips64)
       echo mips ;;
    *)
        echo "Error: unsupported Morph architecture: $MORPH_ARCH" >&2
        exit 1
esac
